// src/views/Home.vue
<template lang="pug">
#home
	section.hero.is-warning.is-bold: .hero-body: .container.has-text-centered.is-size-3
		p รายการตัวกรอง #[strong EasyList] สำหรับประเทศไทย
		p ช่วยคุณปิดกั้นโฆษณาทั้งหลายในเว็บต่างๆของประเทศไทย
	section.section: .container
		h1.title การติดตั้ง
		.is-size-4
			p
				| ติดตั้ง
				|
				b-tooltip(
					:label='abpIntro'
					type='is-dark'
					multilined
					size='is-large'
				)
					a(:href='abpUrl', target='_blank') Adblock Plus
				|
				| หรือ
				|
				b-tooltip(
					:label='uBlockOriginIntro'
					type='is-dark'
					multilined
					size='is-large'
				)
					a(:href='uBlockOriginUrl', target='_blank') uBlock Origin
			p
				| จากนั้นก็เพิ่มไฟล์ Subscription
				|
				a(
					:href='subscriptionUrl',
					target='_blank'
					@click.prevent='copySubscription'
				) easylist-thailand.txt
				|
				| เข้าสู่ Adblock Plus หรือ uBlock Origin ของท่าน
			p.subscription.has-text-centered หรือ #[SubscribeButton(:url='subscriptionUrl', title='EasyList Thailand') กดที่นี่] เพื่อเพิ่มทันที
</template>

<script lang="ts">
import copy from 'clipboard-copy';
import { Component, Vue } from 'vue-property-decorator';

import SubscribeButton from '@/components/SubscribeButton.vue';

@Component({
	name: 'Home',
	components: {
		SubscribeButton
	}
})
export default class Home extends Vue {
	abpUrl = 'https://adblockplus.org/';
	uBlockOriginUrl = 'https://github.com/gorhill/uBlock/#installation';
	subscriptionUrl = 'https://raw.githubusercontent.com/easylist-thailand/easylist-thailand/master/subscription/easylist-thailand.txt';

	abpIntro = 'Surf the web without annoying ads!';
	uBlockOriginIntro = 'Finally, an efficient blocker. Easy on CPU and memory.';

	async copySubscription() {
		await copy(this.subscriptionUrl);
		this.$toast.open('ลิงค์ไฟล์ Subscription ถูกคัดลอกแล้ว');
	}
}
</script>

<style lang="scss" scoped>
.subscription {
	margin: 1em 0;
}
</style>

// src/view/Home.jsx
import React, { Component } from 'react';
import { Card, Tooltip, Row, Col} from 'antd';

import { ABPLink, BlankLink, Space } from '../component';

const ABPUrl = 'https://adblockplus.org/';
const uBlockUrl = 'https://github.com/gorhill/uBlock/#installation';
const subscriptionFileUrl = 'https://raw.githubusercontent.com/easylist-thailand/easylist-thailand/master/subscription/easylist-thailand.txt';

const ABPIntro = 'Surf the web without annoying ads!';
const uBlockIntro = 'Finally, an efficient blocker. Easy on CPU and memory.';

class Home extends Component {
	render() {
		return (
			<div id='home'>
				<Card id='introduction'>
					<p>รายการตัวกรอง <b>EasyList</b> สำหรับประเทศไทย</p>
					<p>ช่วยคุณปิดกั้นโฆษณาทั้งหลายในเว็บต่างๆของประเทศไทย</p>
				</Card>
				<Card id='installation' title='การติดตั้ง'>
					<p>
						ติดตั้ง
						<Space/>
						<Tooltip title={ABPIntro}>
							<span>
								<BlankLink href={ABPUrl}>Adblock Plus</BlankLink>
							</span>
						</Tooltip>
						<Space/>
						หรือ
						<Space/>
						<Tooltip title={uBlockIntro}>
							<span>
								<BlankLink href={uBlockUrl}>uBlock Origin</BlankLink>
							</span>
						</Tooltip>
					</p>
					<p>
						จากนั้นก็เพิ่มไฟล์ Subscription
						<Space/>
						<BlankLink href={subscriptionFileUrl}>easylist-thailand.txt</BlankLink>
						<Space/>
						เข้าสู่ Adblock Plus หรือ uBlock Origin ของท่าน
					</p>

					<Row type='flex' justify='center'>
						<Col>
							หรือ
							<Space/>
							<ABPLink url={subscriptionFileUrl} title='EasyList Thailand'>กดที่นี่</ABPLink>
							<Space/>
							เพื่อเพิ่มทันที
						</Col>
					</Row>
				</Card>
			</div>
		);
	}
}

export default Home;
