// src/views/Home.jsx
import React, { Component } from 'react';

import {
	Container,
	Header,
	Segment
} from 'semantic-ui-react';

import Octicon from 'react-octicon';

import {
	ABPLink,
	BlankLink
} from '../components';

class Home extends Component {
	render() {
		return (
			<Container>
				<Segment basic>
					<Header as='h1' dividing>EasyList Thailand </Header>
					<div className='content'>
						<Segment color='red' size='large' raised>
							<p>รายการตัวกรอง <b>EasyList</b> สำหรับประเทศไทย</p>
							<p>ช่วยคุณปิดกั้นโฆษณาทั้งหลายในเว็บต่างๆของประเทศไทย</p>
						</Segment>
						<Segment color='green' size='large' raised>
							<Header as='h2'>การติดตั้ง</Header>
							<p>ติดตั้ง <BlankLink url='https://adblockplus.org/'>Adblock Plus</BlankLink> หรือ <BlankLink url='https://github.com/gorhill/uBlock/#installation'>uBlock Origin</BlankLink></p>
							<p>จากนั้นก็เพิ่มไฟล์ Subscription <BlankLink url='https://raw.githubusercontent.com/easylist-thailand/easylist-thailand/master/subscription/easylist-thailand.txt'>easylist-thailand.txt</BlankLink> เข้าสู่ Adblock Plus หรือ uBlock Origin ของท่าน</p>

							<Segment basic textAlign='center'>
								หรือ <ABPLink title='EasyList Thailand' url='https://raw.githubusercontent.com/easylist-thailand/easylist-thailand/master/subscription/easylist-thailand.txt'>กดที่นี่</ABPLink> เพื่อเพิ่มทันที
							</Segment>
						</Segment>
					</div>
				</Segment>
				<footer>
					<p id='repo-link'>
						<BlankLink url='https://github.com/easylist-thailand/easylist-thailand'>
							<Octicon name='mark-github' />
							<span>View on GitHub</span>
						</BlankLink>
					</p>
				</footer>
			</Container>
		);
	}
}

export default Home;

// src/views/Home.vue
<template lang="pug">
#home
	section.hero.is-warning.is-bold: .hero-body: .container.has-text-centered.is-size-3
		p รายการตัวกรอง #[strong EasyList] สำหรับประเทศไทย
		p ช่วยคุณปิดกั้นโฆษณาทั้งหลายในเว็บต่างๆของประเทศไทย
	section.section: .container
		h1.title การติดตั้ง
		.is-size-4
			p
				| ติดตั้ง
				|
				b-tooltip(
					:label='abpIntro'
					type='is-dark'
					multilined
					size='is-large'
				)
					a(:href='abpUrl', target='_blank') Adblock Plus
				|
				| หรือ
				|
				b-tooltip(
					:label='uBlockOriginIntro'
					type='is-dark'
					multilined
					size='is-large'
				)
					a(:href='uBlockOriginUrl', target='_blank') uBlock Origin
			p
				| จากนั้นก็เพิ่มไฟล์ Subscription
				|
				a(
					:href='subscriptionUrl',
					target='_blank'
					@click.prevent='copySubscription'
				) easylist-thailand.txt
				|
				| เข้าสู่ Adblock Plus หรือ uBlock Origin ของท่าน
			p.subscription.has-text-centered หรือ #[SubscribeButton(:url='subscriptionUrl', title='EasyList Thailand') กดที่นี่] เพื่อเพิ่มทันที
</template>

<script lang="ts">
import copy from 'clipboard-copy';
import { Component, Vue } from 'vue-property-decorator';

import SubscribeButton from '@/components/SubscribeButton.vue';

@Component({
	name: 'Home',
	components: {
		SubscribeButton
	}
})
export default class Home extends Vue {
	abpUrl = 'https://adblockplus.org/';
	uBlockOriginUrl = 'https://github.com/gorhill/uBlock/#installation';
	subscriptionUrl = 'https://raw.githubusercontent.com/easylist-thailand/easylist-thailand/master/subscription/easylist-thailand.txt';

	abpIntro = 'Surf the web without annoying ads!';
	uBlockOriginIntro = 'Finally, an efficient blocker. Easy on CPU and memory.';

	async copySubscription() {
		await copy(this.subscriptionUrl);
		this.$toast.open('ลิงค์ไฟล์ Subscription ถูกคัดลอกแล้ว');
	}
}
</script>

<style lang="scss" scoped>
.subscription {
	margin: 1em 0;
}
</style>
